"""add file_content to processings

Revision ID: 0c31c8379642
Revises: e2ef58c3f75b
Create Date: 2026-08-07 12:09:39.628913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c31c8379642'
down_revision: Union[str, Sequence[str], None] = 'e2ef58c3f75b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processings', sa.Column('file_content', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processings', 'file_content')
    # ### end Alembic commands ###
