"""add celery_task_id to processings

Revision ID: 71ed2b437cef
Revises: bc45d95e98cb
Create Date: 2026-07-14 11:50:48.873752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71ed2b437cef'
down_revision: Union[str, Sequence[str], None] = 'bc45d95e98cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processings', sa.Column('celery_task_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processings', 'celery_task_id')
    op.drop_constraint(None, 'counterparty_risks', type_='foreignkey')
    # ### end Alembic commands ###
